"""
DEPRECATED — Use NeuroLab Analysis Dashboard instead:
  Export → master_study_data.csv + neuro_study_analysis.sps
  (generated from frontend/src/analysisPlan.js)

Legacy: Generate SPSS syntax from per-file spss_kinematics.csv export.

Usage:
  python gen_spss_syntax.py spss_kinematics.csv --out kinematic_analysis.sps
"""
import warnings
warnings.warn(
    "gen_spss_syntax.py is deprecated. Use Analysis Dashboard → neuro_study_analysis.sps",
    DeprecationWarning,
    stacklevel=1,
)

import sys, os
import pandas as pd

GLOBAL_VARS = [
    "sparc", "trunk_ratio", "shoulder_vert_norm",
    "elbow_angle_mean", "elbow_angle_max",
    "movement_time_sec", "peak_velocity_px_s", "peak_velocity_m_s",
    "shoulder_width_cm", "shoulder_elevation_cm",
    "side_analyzed", "fs_hz",
]

VARIABLE_LABELS = {
    "sparc": "SPARC (smoothness)",
    "trunk_ratio": "Trunk-to-palm displacement ratio",
    "shoulder_vert_norm": "Shoulder vertical excursion (norm)",
    "elbow_angle_mean": "Elbow angle mean (deg)",
    "elbow_angle_max": "Elbow angle max (deg)",
    "movement_time_sec": "Movement time (s)",
    "peak_velocity_px_s": "Peak velocity (px/s)",
    "peak_velocity_m_s": "Peak velocity (m/s)",
    "shoulder_width_cm": "Shoulder width (cm)",
    "shoulder_elevation_cm": "Shoulder elevation (cm)",
    "side_analyzed": "Side analyzed",
    "fs_hz": "Sampling rate (Hz)",
}

PRIMARY_VARS = ["sparc"]

SECONDARY_VARS = [
    "trunk_ratio",
    "shoulder_vert_norm",
    "elbow_angle_mean",
    "movement_time_sec",
    "peak_velocity_px_s",
]


def generate_syntax(csv_path, sps_path):
    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    groups = sorted(df["group"].dropna().unique())
    has_baseline = any(c.startswith("baseline_") for c in df.columns)

    lines = []
    l = lines.append

    l(f"* SPSS Syntax generated by gen_spss_syntax.py")
    l(f"* Source: {os.path.basename(csv_path)}")
    l(f"* Generated for: {', '.join(groups)}")
    l("")

    l("*** 1. OPEN DATASET ***.")
    l(f"GET FILE='{os.path.abspath(csv_path)}'.")
    l("")
    l("EXECUTE.")
    l("DATASET NAME Kinematics WINDOW=FRONT.")
    l("")

    l("*** 2. VARIABLE LABELS ***.")
    for tp in TIMEPOINTS:
        for var in GLOBAL_VARS:
            label = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS {tp}_{var} '{tp.capitalize()}: {label}'.")
    for tp in TIMEPOINTS:
        l(f"VARIABLE LABELS {tp}_file_used '{tp.capitalize()}: Source file'.")
    l("")

    l("VALUE LABELS group")
    for g in groups:
        l(f"  {g} '{g}'")
    l(".")
    l("")

    # Delta score computation
    l("*** 3. COMPUTE DELTA SCORES ***.")
    l("* Post - Pre (intervention effect on affected side).")
    for var in PRIMARY_VARS:
        l(f"COMPUTE delta_{var}_post_pre = post_{var} - pre_{var}.")
        vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
        l(f"VARIABLE LABELS delta_{var}_post_pre 'Post\u2013Pre: {vl}'.")

    if has_baseline:
        l("")
        l("* Baseline - Pre (healthy vs affected at baseline).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_bl_pre = baseline_{var} - pre_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_bl_pre 'Healthy\u2013Pre: {vl}'.")
        l("")
        l("* Post - Baseline (affected after intervention vs healthy).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_post_bl = post_{var} - baseline_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_post_bl 'Post\u2013Healthy: {vl}'.")
    l("EXECUTE.")
    l("")

    # Descriptive statistics
    l("*** 4. DESCRIPTIVE STATISTICS ***.")
    l("DESCRIPTIVES VARIABLES=")
    for tp in TIMEPOINTS:
        for var in PRIMARY_VARS:
            l(f"  {tp}_{var}")
    l("  /STATISTICS=MEAN STDDEV MIN MAX.")
    l("")

    # Repeated measures GLM
    l("*** 5. REPEATED MEASURES ANOVA (Time: Pre vs Post) ***.")
    l("GLM")
    for i, var in enumerate(PRIMARY_VARS):
        sep = "" if i == len(PRIMARY_VARS) - 1 else ""
        l(f"  pre_{var} post_{var} {sep}")
    l("  /WSFACTOR=time 2 Polynomial")
    l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
    l("  /METHOD=SSTYPE(3)")
    l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
    l("  /CRITERIA=ALPHA(.05)")
    l("  /WSDESIGN=time.")
    l("")

    # Between-group comparison
    if len(groups) > 1:
        l("*** 6. MIXED ANOVA (Group x Time) ***.")
        l("GLM")
        for i, var in enumerate(PRIMARY_VARS):
            sep = "" if i == len(PRIMARY_VARS) - 1 else ""
            l(f"  pre_{var} post_{var} {sep}")
        l("  /WSFACTOR=time 2 Polynomial")
        l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
        l("  /METHOD=SSTYPE(3)")
        l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
        l("  /PLOT=PROFILE(time*group)")
        l("  /CRITERIA=ALPHA(.05)")
        l("  /WSDESIGN=time")
        l("  /DESIGN=group.")
        l("")

    # Delta score analysis
    if len(groups) > 1:
        l("*** 7. INDEPENDENT T-TEST ON DELTA SCORES ***.")
        for var in PRIMARY_VARS:
            l(f"T-TEST GROUPS=group(1 2)")
            l(f"  /VARIABLES=delta_{var}_post_pre")
            l(f"  /CRITERIA=CI(.95).")
    l("")

    # Effect size benchmarks
    l("*** 8. PARTIAL ETA-SQUARED INTERPRETATION ***.")
    l("* Small = .01, Medium = .06, Large = .14 (Cohen, 1988).")
    l("")

    # Save final dataset with deltas
    l("*** 9. SAVE DATASET WITH DELTA SCORES ***.")
    l("SAVE OUTFILE='kinematic_with_deltas.sav'.")
    l("EXECUTE.")

    with open(sps_path, "w", encoding="utf-8-sig") as f:
        f.write("\n".join(lines))

    print(f"✓ SPSS syntax written to: {sps_path}")
    print(f"  Groups: {', '.join(groups)}")
    print(f"  Primary variables: {len(PRIMARY_VARS)}")
    print(f"  Lines: {len(lines)}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} spss_kinematics.csv --out kinematic_analysis.sps")
        return
    csv_path = sys.argv[1]
    sps_path = "kinematic_analysis.sps"
    if "--out" in sys.argv:
        idx = sys.argv.index("--out")
        if idx + 1 < len(sys.argv):
            sps_path = sys.argv[idx + 1]

    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        return
    generate_syntax(csv_path, sps_path)


if __name__ == "__main__":
    main()
