"""
gen_spss_syntax.py — Generate SPSS syntax from exported kinematics CSV

Usage:
  .\venv\Scripts\python.exe gen_spss_syntax.py spss_kinematics.csv --out kinematic_analysis.sps
"""

import sys, os
import pandas as pd

GLOBAL_VARS = [
    "total_duration_s", "total_peak_velocity", "total_mean_velocity",
    "total_path_length", "total_lat_range_norm", "total_trunk_palm_ratio",
    "total_max_elbow_deg", "smoothness_pause_pct",
    "trunk_lat_norm", "trunk_vert_norm", "trunk_rot_norm",
    "shoulder_vert_norm",
    "arm_length_norm", "shoulder_width_norm", "baseline_elbow_deg",
    "phases_detected", "side_analyzed", "active_hand_path", "inactive_hand_path",
    "rest_velocity", "idle_threshold",
    "shoulder_width_cm", "arm_length_cm", "total_path_length_cm",
    "total_lat_range_cm", "trunk_lat_cm", "trunk_vert_cm", "trunk_rot_cm",
    "total_depression_cm",
]

# Timepoints to export
TIMEPOINTS = ["pre", "post", "baseline"]

VARIABLE_LABELS = {
    "total_duration_s": "Movement duration (s)",
    "total_peak_velocity": "Peak velocity (norm)",
    "total_mean_velocity": "Mean velocity (norm)",
    "total_path_length": "Total path length (norm)",
    "total_lat_range_norm": "Lateral range (norm)",
    "total_trunk_palm_ratio": "Trunk-to-palm path ratio",
    "total_max_elbow_deg": "Max elbow extension (deg)",
    "smoothness_pause_pct": "Pause time (%)",
    "trunk_lat_norm": "Trunk lateral displacement (norm)",
    "trunk_vert_norm": "Trunk vertical displacement (norm)",
    "trunk_rot_norm": "Trunk rotation (norm)",
    "shoulder_vert_norm": "Shoulder vertical excursion (norm)",
    "arm_length_norm": "Arm length (norm)",
    "shoulder_width_norm": "Shoulder width (pixels)",
    "baseline_elbow_deg": "Baseline elbow angle (deg)",
    "phases_detected": "Number of phases detected",
    "side_analyzed": "Side analyzed",
    "active_hand_path": "Active hand total path (pixels)",
    "inactive_hand_path": "Inactive hand total path (pixels)",
    "rest_velocity": "Rest velocity",
    "idle_threshold": "Idle threshold",
    "shoulder_width_cm": "Shoulder width (cm)",
    "arm_length_cm": "Arm length (cm)",
    "total_path_length_cm": "Total path length (cm)",
    "total_lat_range_cm": "Lateral range (cm)",
    "trunk_lat_cm": "Trunk lateral displacement (cm)",
    "trunk_vert_cm": "Trunk vertical displacement (cm)",
    "trunk_rot_cm": "Trunk rotation (cm)",
    "total_depression_cm": "Shoulder vertical excursion (cm)",
}

PRIMARY_VARS = [
    "total_path_length_cm",
    "total_peak_velocity",
    "smoothness_pause_pct",
    "trunk_vert_cm",
    "trunk_rot_cm",
    "total_depression_cm",
    "total_max_elbow_deg",
    "total_trunk_palm_ratio",
]


def generate_syntax(csv_path, sps_path):
    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    groups = sorted(df["group"].dropna().unique())
    has_baseline = any(c.startswith("baseline_") for c in df.columns)

    lines = []
    l = lines.append

    l(f"* SPSS Syntax generated by gen_spss_syntax.py")
    l(f"* Source: {os.path.basename(csv_path)}")
    l(f"* Generated for: {', '.join(groups)}")
    l("")

    l("*** 1. OPEN DATASET ***.")
    l(f"GET FILE='{os.path.abspath(csv_path)}'.")
    l("")
    l("EXECUTE.")
    l("DATASET NAME Kinematics WINDOW=FRONT.")
    l("")

    l("*** 2. VARIABLE LABELS ***.")
    for tp in TIMEPOINTS:
        for var in GLOBAL_VARS:
            label = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS {tp}_{var} '{tp.capitalize()}: {label}'.")
    for tp in TIMEPOINTS:
        l(f"VARIABLE LABELS {tp}_file_used '{tp.capitalize()}: Source file'.")
    l("")

    l("VALUE LABELS group")
    for g in groups:
        l(f"  {g} '{g}'")
    l(".")
    l("")

    # Delta score computation
    l("*** 3. COMPUTE DELTA SCORES ***.")
    l("* Post - Pre (intervention effect on affected side).")
    for var in PRIMARY_VARS:
        l(f"COMPUTE delta_{var}_post_pre = post_{var} - pre_{var}.")
        vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
        l(f"VARIABLE LABELS delta_{var}_post_pre 'Post\u2013Pre: {vl}'.")

    if has_baseline:
        l("")
        l("* Baseline - Pre (healthy vs affected at baseline).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_bl_pre = baseline_{var} - pre_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_bl_pre 'Healthy\u2013Pre: {vl}'.")
        l("")
        l("* Post - Baseline (affected after intervention vs healthy).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_post_bl = post_{var} - baseline_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_post_bl 'Post\u2013Healthy: {vl}'.")
    l("EXECUTE.")
    l("")

    # Descriptive statistics
    l("*** 4. DESCRIPTIVE STATISTICS ***.")
    l("DESCRIPTIVES VARIABLES=")
    for tp in TIMEPOINTS:
        for var in PRIMARY_VARS:
            l(f"  {tp}_{var}")
    l("  /STATISTICS=MEAN STDDEV MIN MAX.")
    l("")

    # Repeated measures GLM
    l("*** 5. REPEATED MEASURES ANOVA (Time: Pre vs Post) ***.")
    l("GLM")
    for i, var in enumerate(PRIMARY_VARS):
        sep = "" if i == len(PRIMARY_VARS) - 1 else ""
        l(f"  pre_{var} post_{var} {sep}")
    l("  /WSFACTOR=time 2 Polynomial")
    l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
    l("  /METHOD=SSTYPE(3)")
    l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
    l("  /CRITERIA=ALPHA(.05)")
    l("  /WSDESIGN=time.")
    l("")

    # Between-group comparison
    if len(groups) > 1:
        l("*** 6. MIXED ANOVA (Group x Time) ***.")
        l("GLM")
        for i, var in enumerate(PRIMARY_VARS):
            sep = "" if i == len(PRIMARY_VARS) - 1 else ""
            l(f"  pre_{var} post_{var} {sep}")
        l("  /WSFACTOR=time 2 Polynomial")
        l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
        l("  /METHOD=SSTYPE(3)")
        l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
        l("  /PLOT=PROFILE(time*group)")
        l("  /CRITERIA=ALPHA(.05)")
        l("  /WSDESIGN=time")
        l("  /DESIGN=group.")
        l("")

    # Delta score analysis
    if len(groups) > 1:
        l("*** 7. INDEPENDENT T-TEST ON DELTA SCORES ***.")
        for var in PRIMARY_VARS:
            l(f"T-TEST GROUPS=group(1 2)")
            l(f"  /VARIABLES=delta_{var}_post_pre")
            l(f"  /CRITERIA=CI(.95).")
    l("")

    # Effect size benchmarks
    l("*** 8. PARTIAL ETA-SQUARED INTERPRETATION ***.")
    l("* Small = .01, Medium = .06, Large = .14 (Cohen, 1988).")
    l("")

    # Save final dataset with deltas
    l("*** 9. SAVE DATASET WITH DELTA SCORES ***.")
    l("SAVE OUTFILE='kinematic_with_deltas.sav'.")
    l("EXECUTE.")

    with open(sps_path, "w", encoding="utf-8-sig") as f:
        f.write("\n".join(lines))

    print(f"✓ SPSS syntax written to: {sps_path}")
    print(f"  Groups: {', '.join(groups)}")
    print(f"  Primary variables: {len(PRIMARY_VARS)}")
    print(f"  Lines: {len(lines)}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} spss_kinematics.csv --out kinematic_analysis.sps")
        return
    csv_path = sys.argv[1]
    sps_path = "kinematic_analysis.sps"
    if "--out" in sys.argv:
        idx = sys.argv.index("--out")
        if idx + 1 < len(sys.argv):
            sps_path = sys.argv[idx + 1]

    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        return
    generate_syntax(csv_path, sps_path)


if __name__ == "__main__":
    main()
