"""
DEPRECATED — Use NeuroLab Analysis Dashboard instead:
  Export → master_study_data.csv + neuro_study_analysis.sps
  (generated from frontend/src/analysisPlan.js)

Legacy: Generate SPSS syntax from per-file spss_kinematics.csv export.

Usage:
  python gen_spss_syntax.py spss_kinematics.csv --out kinematic_analysis.sps
"""
import warnings
warnings.warn(
    "gen_spss_syntax.py is deprecated. Use Analysis Dashboard → neuro_study_analysis.sps",
    DeprecationWarning,
    stacklevel=1,
)

import sys, os
import pandas as pd

GLOBAL_VARS = [
    "nvp", "straightness", "pause_time_sec", "number_of_stops",
    "trunk_ratio", "shoulder_elevation_palm_ratio", "shoulder_elevation_cm",
    "peak_velocity_cm_s", "hand_displacement_cm",
    "elbow_angle_mean_deg", "movement_time_sec",
    "peak_elbow_ang_vel_deg_s",
]

VARIABLE_LABELS = {
    "task_complete": "Task completed (all expected phases)",
    "task_completion_ratio": "Task completion ratio (0-1)",
    "nvp_reach": "NVP reach window (sips excluded)",
    "nvp_transport": "NVP transport / drink lift phase",
    "nvp_drink": "NVP drink (table to peak height)",
    "nvp_return": "NVP return to table",
    "nvp_total": "NVP sum of reach + transport + return",
    "lift_height_sw": "Peak lift height (shoulder widths)",
    "lift_height_cm": "Peak lift height (cm; table 85 cm scale)",
    "drink_lift_height_sw": "Drink lift height table to peak (SW)",
    "drink_lift_height_cm": "Drink lift height table to peak (cm; table 85 cm)",
    "nvp": "NVP primary (= reach; sips excluded)",
    "nvp_full_task": "NVP full task including sip approaches (exploratory)",
    "sip_bout_count": "Sip / mouth approaches during drink (descriptive)",
    "straightness": "Path straightness (primary = reach)",
    "straightness_reach": "Path straightness (reach window)",
    "pause_time_sec": "Path pause time (s; dwell/sips excluded)",
    "pause_time_sec_reach": "Pause time path only (reach; grasp dwell excluded)",
    "pause_time_sec_total": "Pause time including functional dwell (s)",
    "grasp_dwell_sec": "Terminal grasp fixation dwell (s)",
    "functional_hold_sec": "Functional hold: grasp + mouth/face (s)",
    "number_of_stops": "Number of path stops",
    "number_of_stops_reach": "Number of path stops (reach)",
    "trunk_ratio": "Trunk-to-palm displacement ratio",
    "shoulder_elevation_palm_ratio": "Shoulder elevation (palm anchor)",
    "shoulder_elevation_cm": "Shoulder elevation (cm; table 85 cm scale)",
    "peak_velocity_cm_s": "Peak hand velocity (cm/s; table 85 cm scale)",
    "hand_displacement_cm": "Hand displacement (cm; table 85 cm scale)",
    "elbow_angle_mean_deg": "Elbow angle mean (deg)",
    "movement_time_sec": "Movement time (s)",
    "peak_elbow_ang_vel_deg_s": "Peak elbow angular velocity (°/s)",
    "tremor_8_12hz_power": "Tremor 8–12 Hz relative power (hand speed)",
    "index_tremor_8_12hz_power": "Index finger tremor 8–12 Hz relative power",
    "adl_tremor_8_12hz_power": "Tremor 8–12 Hz relative power (ADL phase)",
    "tremor_peak_freq_hz": "Dominant tremor frequency in 8–12 Hz band (Hz)",
    "movement_quality_index": "Movement quality index 0–100 (composite)",
}

PRIMARY_VARS = ["nvp", "straightness", "pause_time_sec", "number_of_stops"]

TIMEPOINTS = ["pre", "post", "baseline"]

SECONDARY_VARS = [
    "trunk_ratio",
    "shoulder_elevation_palm_ratio",
    "elbow_angle_mean_deg",
    "movement_time_sec",
    "peak_elbow_ang_vel_deg_s",
]

EXPLORATORY_VARS = [
    "tremor_8_12hz_power",
]


def generate_syntax(csv_path, sps_path):
    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    groups = sorted(df["group"].dropna().unique())
    has_baseline = any(c.startswith("baseline_") for c in df.columns)

    lines = []
    l = lines.append

    l(f"* SPSS Syntax generated by gen_spss_syntax.py")
    l(f"* Source: {os.path.basename(csv_path)}")
    l(f"* Generated for: {', '.join(groups)}")
    l("")

    l("*** 1. OPEN DATASET ***.")
    l(f"GET FILE='{os.path.abspath(csv_path)}'.")
    l("")
    l("EXECUTE.")
    l("DATASET NAME Kinematics WINDOW=FRONT.")
    l("")

    l("*** 2. VARIABLE LABELS ***.")
    for tp in TIMEPOINTS:
        for var in GLOBAL_VARS:
            label = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS {tp}_{var} '{tp.capitalize()}: {label}'.")
    for tp in TIMEPOINTS:
        l(f"VARIABLE LABELS {tp}_file_used '{tp.capitalize()}: Source file'.")
    l("")

    l("VALUE LABELS group")
    for g in groups:
        l(f"  {g} '{g}'")
    l(".")
    l("")

    # Delta score computation
    l("*** 3. COMPUTE DELTA SCORES ***.")
    l("* Post - Pre (intervention effect on affected side).")
    for var in PRIMARY_VARS:
        l(f"COMPUTE delta_{var}_post_pre = post_{var} - pre_{var}.")
        vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
        l(f"VARIABLE LABELS delta_{var}_post_pre 'Post\u2013Pre: {vl}'.")

    if has_baseline:
        l("")
        l("* Baseline - Pre (healthy vs affected at baseline).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_bl_pre = baseline_{var} - pre_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_bl_pre 'Healthy\u2013Pre: {vl}'.")
        l("")
        l("* Post - Baseline (affected after intervention vs healthy).")
        for var in PRIMARY_VARS:
            l(f"COMPUTE delta_{var}_post_bl = post_{var} - baseline_{var}.")
            vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
            l(f"VARIABLE LABELS delta_{var}_post_bl 'Post\u2013Healthy: {vl}'.")
    l("EXECUTE.")
    l("")

    # Descriptive statistics
    l("*** 4. DESCRIPTIVE STATISTICS ***.")
    l("DESCRIPTIVES VARIABLES=")
    for tp in TIMEPOINTS:
        for var in PRIMARY_VARS:
            l(f"  {tp}_{var}")
    l("  /STATISTICS=MEAN STDDEV MIN MAX.")
    l("")

    # Repeated measures GLM
    l("*** 5. REPEATED MEASURES ANOVA (Time: Pre vs Post) ***.")
    l("GLM")
    for i, var in enumerate(PRIMARY_VARS):
        sep = "" if i == len(PRIMARY_VARS) - 1 else ""
        l(f"  pre_{var} post_{var} {sep}")
    l("  /WSFACTOR=time 2 Polynomial")
    l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
    l("  /METHOD=SSTYPE(3)")
    l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
    l("  /CRITERIA=ALPHA(.05)")
    l("  /WSDESIGN=time.")
    l("")

    # Between-group comparison
    if len(groups) > 1:
        l("*** 6. MIXED ANOVA (Group x Time) ***.")
        l("GLM")
        for i, var in enumerate(PRIMARY_VARS):
            sep = "" if i == len(PRIMARY_VARS) - 1 else ""
            l(f"  pre_{var} post_{var} {sep}")
        l("  /WSFACTOR=time 2 Polynomial")
        l("  /MEASURE=" + " ".join(var.upper() for var in PRIMARY_VARS))
        l("  /METHOD=SSTYPE(3)")
        l("  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY")
        l("  /PLOT=PROFILE(time*group)")
        l("  /CRITERIA=ALPHA(.05)")
        l("  /WSDESIGN=time")
        l("  /DESIGN=group.")
        l("")

    # Delta score analysis
    if len(groups) > 1:
        l("*** 7. INDEPENDENT T-TEST ON DELTA SCORES ***.")
        for var in PRIMARY_VARS:
            l(f"T-TEST GROUPS=group(1 2)")
            l(f"  /VARIABLES=delta_{var}_post_pre")
            l(f"  /CRITERIA=CI(.95).")
    l("")

    # Effect size benchmarks
    l("*** 8. PARTIAL ETA-SQUARED INTERPRETATION ***.")
    l("* Small = .01, Medium = .06, Large = .14 (Cohen, 1988).")
    l("")

    l("*** 10. EXPLORATORY TREMOR (no alpha correction — interpret cautiously) ***.")
    for var in EXPLORATORY_VARS:
        vl = VARIABLE_LABELS.get(var, var.replace("_", " "))
        l(f"COMPUTE delta_{var}_post_pre = post_{var} - pre_{var}.")
        l(f"VARIABLE LABELS delta_{var}_post_pre 'Post\u2013Pre: {vl}'.")
    l("EXECUTE.")
    l("DESCRIPTIVES VARIABLES=")
    for var in EXPLORATORY_VARS:
        l(f"  pre_{var} post_{var}")
    l("  /STATISTICS=MEAN STDDEV MIN MAX.")
    l("")

    # Save final dataset with deltas
    l("*** 11. SAVE DATASET WITH DELTA SCORES ***.")
    l("SAVE OUTFILE='kinematic_with_deltas.sav'.")
    l("EXECUTE.")

    with open(sps_path, "w", encoding="utf-8-sig") as f:
        f.write("\n".join(lines))

    print(f"✓ SPSS syntax written to: {sps_path}")
    print(f"  Groups: {', '.join(groups)}")
    print(f"  Primary variables: {len(PRIMARY_VARS)}")
    print(f"  Lines: {len(lines)}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} spss_kinematics.csv --out kinematic_analysis.sps")
        return
    csv_path = sys.argv[1]
    sps_path = "kinematic_analysis.sps"
    if "--out" in sys.argv:
        idx = sys.argv.index("--out")
        if idx + 1 < len(sys.argv):
            sps_path = sys.argv[idx + 1]

    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        return
    generate_syntax(csv_path, sps_path)


if __name__ == "__main__":
    main()
